### ISSUE TITLE
Other flashlight related issues

### ISSUE THREAD

**Issue by yNaht** [Shaosil/LethalCompanyMods-FlashlightFix#1]
Just curios as to if this mod could potentially fix another issue i've seen with flashlights being on when not supposed to be. i'm not sure if its directly related to the walkie-talkie reserved slot mod but sometimes the flashlight is actually on after switching to the radio though it doesnt look on.

**Comment by Shaosil** [comment]
So far I've tested it for a few hours and it _might_ have fixed that (and other) issues too. Actually, the entire problem was somehow related to holding a walkie in your inventory in the first place. For some reason, that triggers a "use third action" on the flashlight in some cases, which toggles it on or off.

So yeah I'm hoping this is a fix-all solution, but if I find other bugs with it I'll see if I can fix those as well.
