### ISSUE TITLE
FlashlightFix-1.0.4 Bug

### ISSUE THREAD

**Issue by ko0416** [Shaosil/LethalCompanyMods-FlashlightFix#2]
I was using FlashlightFix-1.0.4, ReservedItemSlotCore 1.6.7 and ReservedFlashslot 1.5.1.
There is a bug that if you hold 2 or more flashlights, you cannot turn any of it on.

I rolled back to FlashlightFix-1.0.3 and the bug is gone.

**Comment by Shaosil** [comment]
Thanks for the info, I'll look into it as soon as I can.

**Comment by Shaosil** [comment]
Fixed in v.1.0.5. But keep in mind, ReservedFlashlightSlot does have a bug on their own that turns off 2nd+ flashlights when equipping them. But at least you should be able to turn them back on now :)
