### ISSUE TITLE
Laser Pointer doubling up effect

### ISSUE THREAD

**Issue by KleskReaver** [Shaosil/LethalCompanyMods-FlashlightFix#4]
Just want to report my findings with the Laser Pointer object in the game

when you turn on a Laser Pointer, scroll mouse wheel to a different hotbar slot, then scroll back to the Laser Pointer
you will have a 2x laser effect on the wall (see screenshot)

I tested this with FlashlightFix disabled and its only possible to have 1 laser effect at a time, it looks like the vanilla behaviour is the same as the torch where it places the laser effect in a fixed position when its currently not selected on the hotbar, then has the effect in a different position when holding it in your hand, but not both at the same time.

The doubling up effect has a work-around with "TreatLaserPointerAsFlashlights" config setting, I am getting this issue when it is set to "false", however, when it is set to "true" the issue seems to be fixed!

![20240131223157_1](https://github.com/Shaosil/LethalCompanyMods-FlashlightFix/assets/6572447/e5f2f71c-c7a6-4387-8905-b1eeb59f90db)

hope this info helps
cheers!

**Comment by Shaosil** [comment]
Basically just did a rewrite and v1.1.0 should be going live shortly which fixes this (and adds overall stability to the mod)
